# Generated by Django 3.0.8 on 2020-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=40)),
                ('data', models.DateField()),
                ('horario_entrada', models.TimeField(verbose_name='Horário entrada')),
                ('horario_saida', models.TimeField(verbose_name='Horário saída')),
                ('servico', models.TextField()),
            ],
        ),
    ]
