# Generated by Django 3.0.8 on 2020-08-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário entrada'),
        ),
        migrations.AlterField(
            model_name='register',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário saída'),
        ),
        migrations.AlterField(
            model_name='register',
            name='servico',
            field=models.TextField(blank=True),
        ),
    ]
